#!/bin/sh
cat <<EOF

This Vagrant Box is provided for free to the community by BERGIA Solutions.
  ____  _____ ____   ____ ___    _           
 | __ )| ____|  _ \ / ___|_ _|  / \          
 |  _ \|  _| | |_) | |  _ | |  / _ \         
 | |_) | |___|  _ <| |_| || |_/ ___ \        
 |____/|_____|_| \_\____|____/_/   \_\       
  / ___|  ___ | |_   _| |_(_) ___  _ __  ___ 
  \___ \ / _ \| | | | | __| |/ _ \| '_ \/ __|
   ___) | (_) | | |_| | |_| | (_) | | | \___\\
  |____/ \___/|_|\__,_|\__|_|\___/|_| |_|___/
                                             
	R&D Software engineering consulting 
	https://bergia-solutions.com

	Contact us if you need help with robotics, autonomous systems,
	ROS-based stacks and data science projects !

	To report bugs, improvement suggestions, or to get involved :
	https://github.com/bergia-solutions/vagrant_ros1

EOF
